# config/services.yaml
parameters:
    LIMIT_PAR_PAGE: 5

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Enregistrement explicite de tes services
    App\Service\Impl\CommandeServiceImpl:
        public: true

    # Alias pour l'interface - lie l'interface à l'implémentation
    App\Service\CommandeService:
        alias: App\Service\Impl\CommandeServiceImpl
        public: true