# config/services.yaml
parameters:
    LIMIT_PAR_PAGE: 5

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Service\Impl\CommandeServiceImpl:
        public: true

    App\Service\CommandeService:
        alias: App\Service\Impl\CommandeServiceImpl
        public: true
    App\Service\Impl\LivraisonServiceImpl:
        arguments:
            $em: '@doctrine.orm.entity_manager'
            $commandeRepository: '@App\Repository\CommandeRepository'
            $zoneRepository: '@App\Repository\ZoneRepository'
            $livreurRepository: '@App\Repository\LivreurRepository'
    
    App\Service\LivraisonService: '@App\Service\Impl\LivraisonServiceImpl'